on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up go
      uses: actions/setup-go@v3

    - name: Build container image /w kaniko
      uses: aevea/action-kaniko@master
      with:
        image: waitfor
        tag: latest
        registry: ghcr.io
        password: ${{secrets.CI_REGISTRY_PASSWORD}}