on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build container image /w kaniko
      uses: aevea/action-kaniko@master
      with:
        tag: ${{ github.head_ref || github.ref_name }}
        registry: ghcr.io
        password: ${{secrets.CI_REGISTRY_PASSWORD}}